### ISSUE TITLE
question about the lava-partitioning installation

### ISSUE THREAD

**Issue by ChinJCheung** [cadeleeuw/twas-validity-scripts2022#1]
Hi,
I have a question about the **lava-partitioning** installation, I meet a error:
--------
g++ -diag-disable=remark -w2 -o2 -c src/ Ldblock.cpp -o src/ldblock.o
g++: error: unrecognized command line option ’-w2‘; did you mean‘-w’?
make： *** [src/ldblock.o] Error 1
-----
so , I want to know what is w2, it seem to unrecognoized?

**Comment by cadeleeuw** [comment]
Hi,

The -w flags are compiler flags that determine the level of warnings that are shown during compilation. I usually use a different compiler, sometimes they have different flags. This must be one that G++ doesn't recognise. 

To fix it, you can just edit the makefile and change the -w2 to -w, it should work afterwards.

**Comment by ChinJCheung** [comment]
Hi, 
I change the -w2 to -w, but I meet another problem in src/ldblock.cpp:3:0, as follows:

g++ -diag-disable=remark -w -O2  -c src/ldblock.cpp -o src/ldblock.o
cc1plus: warning: unrecognized gcc debugging option: i [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: g [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: - [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: d [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: i [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: s [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: b [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: l [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: e [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: = [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: r [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: e [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: m [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: r [enabled by default]
cc1plus: warning: unrecognized gcc debugging option: k [enabled by default]
In file included from src/ldblock.cpp:3:0:
src/global.h: In function ‘void error(const string&, int)’:
src/global.h:14:12: error: ‘exit’ was not declared in this scope
   exit(code);
            ^
make: *** [src/ldblock.o] Error 1

I want to know how I should change the src/ldblock.o ?

**Comment by ChinJCheung** [comment]
I have resolved.

**Comment by yybgood** [comment]
1. edit file src/global,h  add "#include <cstdlib>"
2. edit file makefile , l`CXX_FLAGS=-diag-disable=remark` -fpermissive -w -O2`
