### ISSUE TITLE
GTEx files 

### ISSUE THREAD

**Issue by karpat90** [cadeleeuw/twas-validity-scripts2022#2]
Hello!

I am interested in using your package in order to elucidate the relationship between gene expression and traits. Are there any plans to release GTEx v8 eQTL and sQTL input files? 

Thank you

**Comment by cadeleeuw** [comment]
Hi,

We are planning to release some eQTL files, though the format and timeline for that is still to be finalized. I am currently off from work, but if you email me directly (see here: https://ctg.cncr.nl/) I will be able to provide you more information on this after the 14th of August.

Best,
Christiaan de Leeuw
